### ISSUE TITLE
xap controller error in Home Assistant

### ISSUE THREAD

**Issue by RolandWijnen** [jslove/xap_controller#2]
Hi Jay, 

Great that you've written the xap_controller for Home Assistant. I have a XAP400 connected to various small amps that I can switch on and off using an Arduino (MQTT) powered 8 relay board. All of this is working nicely with Home Assistant and the XAP400 also works with the G-Ware software. I can route audio all through the house and garden :-) I'm now trying to use your xap_controller, with the following settings in configuration.yaml:

- platform: xap_controller
    path: /dev/ttyUSB1
    name: MyXAP400
    scan_interval: 30
    stereo: 0
    zones:
      'Living Room & Kitchen':
        - 1
        - 2
      'Veranda & Terrace':
        - 3
        - 4
      'Bathroom & Master bedroom':
        - 5
        - 6
      'Shed':
        - 7
      'Hassio':
        - 8
      'Workroom':
        - 9
    sources:
      'Mic 1st floor':
        - 1
      'Hassio':
        - 2
      'Hifiset': 
        - 3
        - 4
      'Echo':
        - 5
        - 6
      'Volumio':
        - 7
        - 8

When I run this code, I get the following error:

Error while setting up platform xap_controller
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/xap_controller.py", line 201, in setup_platform
    hass, xapconn, source_name, source_input)
  File "/config/custom_components/media_player/xap_controller.py", line 232, in __init__
    self._volume = self.get_volume_level()
  File "/config/custom_components/media_player/xap_controller.py", line 327, in get_volume_level
    gain = self._xapx00.getPropGain(vinp['CHAN'], group="I", unitCode = vinp['UNIT'])
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 87, in stereoFunc
    res = func(*args, **kwargs)
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 354, in getPropGain
    stereo=0)
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 87, in stereoFunc
    res = func(*args, **kwargs)
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 330, in getMaxGain
    if is_number(resp):
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 112, in is_number
    return s.replace('.','',1).replace('-','',1).isdigit()
AttributeError: 'NoneType' object has no attribute 'replace'

Can you help me out here? Should I specify somewhere that I have a XAP400 instead of the XAP800? Or tune some settings with the G-Ware software. Looking forward to your response!

Thanks, Roland.

**Comment by jslove** [comment]
You're correct.
I added an config parameter:  XAPType: XAP400 (or XAP800).
I don't have an XAP400 to test, so let me know if yo have any issues.

**Comment by RolandWijnen** [comment]
Hi Jay, 

Great, many thanks for your quick response and fix. I've added the XAPType: XAP400 to my config. I now get the following error:

Error while setting up platform xap_controller
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/xap_controller.py", line 214, in setup_platform
    hass, xapconn, source_name, source_input)
  File "/config/custom_components/media_player/xap_controller.py", line 245, in __init__
    self._volume = self.get_volume_level()
  File "/config/custom_components/media_player/xap_controller.py", line 340, in get_volume_level
    gain = self._xapx00.getPropGain(vinp['CHAN'], group="I", unitCode = vinp['UNIT'])
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 83, in stereoFunc
    res = func(*args, **kwargs)
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 378, in getPropGain
    raise XAPCommError("resp={}".format(resp))
XAPX00.XAPX00.XAPCommError: resp=A

Any idea what goes wrong? Let me know if you have a suggestion where to look and I'll test that out. Greetz, Roland.

**Comment by jslove** [comment]
I'll need you to turn on debug output for the XAPX00 and xap_controller.  I'm not looking at my config right now, but if you go to your configuration.yaml you need to add something like:

logger:
  logs:
    XAPX00.XAPX00: debug
   media_player.xap_controller: debug

I'll check my actual debug config section later today if those aren't the right modules.  The xap_controller line may need custom_components. added to the front, I can't remember.

**Comment by RolandWijnen** [comment]
Ok, I turned on logging. This is what shows up:

2019-02-05 19:52:33 INFO (SyncWorker_2) [XAPX00.XAPX00] XAPX00 version: 0.2.6
2019-02-05 19:52:33 DEBUG (SyncWorker_2) [XAPX00.XAPX00] sending command: #70 UID  
2019-02-05 19:52:33 DEBUG (SyncWorker_2) [XAPX00.XAPX00] Response LVL 7 L I -49.35
2019-02-05 19:52:33 DEBUG (SyncWorker_2) [XAPX00.XAPX00] Response OK> #70 LVL 7 L A -39.70
2019-02-05 19:52:33 DEBUG (SyncWorker_2) [XAPX00.XAPX00] sending command: #7None MAX 1 I 
2019-02-05 19:52:33 DEBUG (SyncWorker_2) [XAPX00.XAPX00] Response A -37.89
2019-02-05 19:52:33 DEBUG (SyncWorker_2) [XAPX00.XAPX00] Response OK> #70 LVL 8 L I -47.10
2019-02-05 19:52:33 DEBUG (SyncWorker_2) [XAPX00.XAPX00] sending command: #7None GAIN 1 I 
2019-02-05 19:52:34 DEBUG (SyncWorker_2) [XAPX00.XAPX00] Response 0 LVL 6 L A -92.48
2019-02-05 19:52:34 DEBUG (SyncWorker_2) [XAPX00.XAPX00] Response OK> #70 LVL 7 L I -50.46

2019-02-05 19:52:34 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform xap_controller
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/xap_controller.py", line 214, in setup_platform
    hass, xapconn, source_name, source_input)
  File "/config/custom_components/media_player/xap_controller.py", line 245, in __init__
    self._volume = self.get_volume_level()
  File "/config/custom_components/media_player/xap_controller.py", line 340, in get_volume_level
    gain = self._xapx00.getPropGain(vinp['CHAN'], group="I", unitCode = vinp['UNIT'])
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 83, in stereoFunc
    res = func(*args, **kwargs)
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 378, in getPropGain
    raise XAPCommError("resp={}".format(resp))
XAPX00.XAPX00.XAPCommError: resp=I

Any idea? I'll try to do some digging myself too...

**Comment by jslove** [comment]
I think I see the issue, I'll look into it in a few hours.
Jay

**Comment by jslove** [comment]
Added a change that may fix it for you.  Please also add to your logs:
custom_components.media_player.xap_controller: debug

(Assuming you put xap_controller in custom_components)
Jay

**Comment by RolandWijnen** [comment]
Hi Jay, 

The code is setting up the first source and then runs into trouble. It seems to get stuck in the getPropGain(self, channel, group="I", unitCode=0) function. The response from the XAP400 seems to be 'A' while the code is expecting a number. 

Here's the log:

2019-02-06 10:26:14 DEBUG (SyncWorker_10) [custom_components.media_player.xap_controller] Conf file sources: OrderedDict([('Hassio', [1]), ('Mic Upstairs', [2]), ('Hifiset', [3, 4]), ('Echo', [5, 6]), ('Volumio', [7, 8])])
2019-02-06 10:26:15 DEBUG (SyncWorker_10) [custom_components.media_player.xap_controller] XAPX00 version: 0.2.6
2019-02-06 10:26:15 DEBUG (SyncWorker_10) [custom_components.media_player.xap_controller] XAP Type: XAP400
2019-02-06 10:26:15 INFO (SyncWorker_10) [XAPX00.XAPX00] XAPX00 version: 0.2.6
2019-02-06 10:26:15 DEBUG (SyncWorker_10) [XAPX00.XAPX00] sending command: #70 UID  
2019-02-06 10:26:15 DEBUG (SyncWorker_10) [XAPX00.XAPX00] Response  #70 LVL 7 L I -70.83

2019-02-06 10:26:15 DEBUG (SyncWorker_10) [custom_components.media_player.xap_controller] Setting Up Source Hassio
2019-02-06 10:26:15 DEBUG (SyncWorker_10) [XAPX00.XAPX00] sending command: #70 MAX 1 I 
2019-02-06 10:26:15 DEBUG (SyncWorker_10) [XAPX00.XAPX00] Response 

2019-02-06 10:26:15 DEBUG (SyncWorker_10) [XAPX00.XAPX00] Response OK> #70 LVL 6 L A -89.68

2019-02-06 10:26:15 DEBUG (SyncWorker_10) [XAPX00.XAPX00] sending command: #70 GAIN 1 I 
2019-02-06 10:26:15 DEBUG (SyncWorker_10) [XAPX00.XAPX00] Response > #70 LVL 8 L A -60.44

2019-02-06 10:26:16 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform xap_controller
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/xap_controller.py", line 214, in setup_platform
    hass, xapconn, source_name, source_input)
  File "/config/custom_components/media_player/xap_controller.py", line 245, in __init__
    self._volume = self.get_volume_level()
  File "/config/custom_components/media_player/xap_controller.py", line 336, in get_volume_level
    gain = self._xapx00.getPropGain(vinp['CHAN'], group="I", unitCode = vinp['UNIT'])
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 83, in stereoFunc
    res = func(*args, **kwargs)
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 378, in getPropGain
    raise XAPCommError("resp={}".format(resp))
XAPX00.XAPX00.XAPCommError: resp=A

Grtz, Roland.

**Comment by jslove** [comment]
What's confusing is that your unit is responding to a command that wasn't sent.  The code sends a UID and then a MAX command and the response should be a UID and then MAX response (the response is the same as the command sent), but the response in your log is a LVL command.  Do you have anything else trying to use the serial port or communicate with the unit at the same time?

Could you check the setting for Serial Echo? It should be On/1.  Looks like you can check it from the GWare software if you have that, in the Configure Unit Properties dialog.  I need to add a check to my code to make sure its on/turn it on.  The default is on, but maybe it got changed.

**Comment by RolandWijnen** [comment]
Hi Jay, 

I've made progress after updating the firmware from the XAP400 to 2.0.3! Yeah!! I also checked the Serial Echo setting and that is On. Now the sources are being successfully setup. I do only see one zone (Living). Also, if I select the sources 'Echo' en 'Mopidy' from my config file, it does not work. Selecting the other sources does work. 

I've attached the log as a separate file. 

[xap_controller.log](https://github.com/jslove/xap_control/files/2838745/xap_controller.log)

Could it also be that the communication (Serial-to-USB cable) is hampering a bit, causing these errors. Or does the code, re-send commands that are not acknowledged?  

Cheers, Roland.

**Comment by jslove** [comment]
I made a change to correct the error on Inputs above #4, hopefully that'll fix it.

The Serial-to-USB adapter shouldn't be an issue, that's what I use as well.

**Comment by RolandWijnen** [comment]
Hi Jay, 

We're getting there... new log attached :-)

[xap_controller_2.log](https://github.com/jslove/xap_control/files/2840036/xap_controller_2.log)

Grtz, Roland.

**Comment by jslove** [comment]
Sorry, stupid error.  Try it now.

**Comment by RolandWijnen** [comment]
Tried it. I got an error related to this line in xap_controller.py

435 ON = 3 if (type(XIN) is int and XIN <= (self._xapx00.matrixGeo-4)) else 1

I fixed this myself by changing the argument matrixGeo to MatrixGeo because I saw you define it with capital M in XAPX00.py. 

Still the code runs into trouble when setting up the second source. Here is the log.

[xap_controller_3.log](https://github.com/jslove/xap_control/files/2840749/xap_controller_3.log)

Let me know if if there is code I could fiddle around with myself to get to the bottom of this. Thanks so much for fixing errors so far.

**Comment by jslove** [comment]
Ok, there is some other slight difference in the 400 vs 800 commands I’ll
have to figure out. I won’t be able to look at it today though.
Sorry for the challenges!

**Comment by RolandWijnen** [comment]
No problem, Jay! It's a lot of fun to get all of this working... In the meantime, I have plenty of other smarthome stuff to work on :-)

**Comment by jslove** [comment]
OK, I think that last one was just a plain old rare bug, related to float vs scientific notation.  Try the latest version when you get a chance.
Jay

**Comment by RolandWijnen** [comment]
Hi Jay, 

I tried it out and I see it returns a value in scientific notation. Here's part of the log:


2019-02-08 09:40:48 DEBUG (SyncWorker_16) [XAPX00.XAPX00] setPropGain: linear:0.10000000115129257, max:20.0, db:8.696e-05
2019-02-08 09:40:48 DEBUG (SyncWorker_16) [XAPX00.XAPX00] sending command: #70 GAIN 3 O 8.696e-05 A 
2019-02-08 09:40:48 DEBUG (SyncWorker_16) [XAPX00.XAPX00] Response 

2019-02-08 09:40:48 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform xap_controller
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/xap_controller.py", line 223, in setup_platform
    hass, xapconn, zonesources, zone_name, outputs)])
  File "/config/custom_components/media_player/xap_controller.py", line 390, in __init__
    self._sync_volume_level()
  File "/config/custom_components/media_player/xap_controller.py", line 528, in _sync_volume_level
    self.set_volume_level(volume)
  File "/config/custom_components/media_player/xap_controller.py", line 537, in set_volume_level
    unitCode = XUNIT)
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 83, in stereoFunc
    res = func(*args, **kwargs)
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 405, in setPropGain
    unitCode=unitCode, rtnCount=2)[0]
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 265, in XAPCommand
    res = self.readResponse(numElements = rtnCount, serial_conn=serialconn)
  File "/config/deps/lib/python3.6/site-packages/XAPX00/XAPX00.py", line 233, in readResponse
    raise XAPRespError(resp)
XAPX00.XAPX00.XAPRespError: ERROR - Argument error.

**Comment by jslove** [comment]
Was that with version 0.2.8 of XAPX00?

Nevermind, I see the error.  Try it now.

**Comment by RolandWijnen** [comment]
Hi Jay, 

It's working now! Yeah! Many thanks!

<img width="1680" alt="screenshot 2019-02-09 01 08 09" src="https://user-images.githubusercontent.com/24925747/52512894-918f6d80-2c07-11e9-8e35-54ee35ea2304.png">

I can now play around with this. Any cool automations or ideas to share from your setup?

**Comment by jslove** [comment]
Great!  Glad its working.  

I don't have anything particularly interesting in my setup, other than I'm up to 3 linked XAP units now.  Let me know if you come up with something impressive.
